version: '3.4'
services:
  nexus:
    image: sonatype/nexus3:latest
    ports: 
      - "8081:8081"
      - "8082:8082"
    volumes:
      - type: volume
        source: nexus_data
        target: /nexus-data

volumes:
  nexus_data: