version: "3"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data: