entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}

log:
  filePath: "/traefik/logs/traefik.log"
  level: DEBUG
        
providers:
  file:
    directory: /traefik/conf
    watch: true
  docker: {}
api:
  insecure: true
  dashboard: true
  debug: true