version: '3.7'

services:
  gitea:
    image: gitea/gitea:1.13.0
    volumes: 
        - "gitea_data:/data"
    ports: 
      - "10022:22"
      - "3000:3000"
    environment: 
      - ROOT_URL="http://localhost:3000"
  jenkins:
    #image: jenkins/jenkins:lts
    build: jenkins/.
    volumes: 
      - "jenkins_data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment: 
      - JENKINS_OPTS="--prefix=/jenkins"
  
  nexus:
    image: sonatype/nexus3:latest
    ports: 
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - NEXUS_CONTEXT=nexus
     
  httpd:
    image: httpd:2.4
    ports: 
        - 80:80
    #    - 8443:443
    volumes: 
        - ./htdocs:/usr/local/apache2/htdocs/
        - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

volumes: 
  gitea_data:
  jenkins_data:
  nexus_data:
#  artifactory_data: