version: '3.7'

services:
  gitea:
    image: gitea/gitea:1.13.0
    volumes: 
        - "gitea_data:/data"
    ports: 
      - "10022:22"
      - "3000:3000"
    environment: 
      - ROOT_URL="http://localhost:3000"
  nginx:
    image: nginx:latest
    ports: 
        - 80:80
        #- 443:443
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./htdocs/:/usr/share/nginx/html:ro

volumes: 
  gitea_data:
