= Simple Hello World

Using default https://hub.docker.com/_/httpd[http image] from docker hub. 

Create and start container with name apache-hello-world

    docker run -dit --name apache-hello-world -p 8080:80 -v "$PWD/htdocs":/usr/local/apache2/htdocs/ httpd:2.4

Showing the logs, stopping and starting apache-hello-world container.

    docker logs -f apache-hello-world 
    docker stop apache-hello-world 
    docker start apache-hello-world

Accessing the sample page from this container via http://localhost:8080 .

== customizing the default httpd.conf

. extract the default httpd.conf out of the image

    $ docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > conf/httpd.conf

. creating image with mounted cusomized httpd.conf

    docker run -dit --name apache-hello-world -p 8080:80 -v "$PWD/htdocs":/usr/local/apache2/htdocs/ -v "$PWD/conf/httpd.conf":/usr/local/apache2/conf/httpd.conf httpd:2.4

== Running httpd with docker compose

start and stop with compose

    docker-compose up -d 
    docker-compose down

generating self-signed certificate, see also https://www.sslshopper.com/article-most-common-openssl-commands.html[SSL-Howto]

    [openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout conf/server.key -out conf/server.crt

accessing the container with https via https://localhost:8443

.docker-compse.yml
[source,yml]
----
include::docker-compose.yml[]
----

== generating your own CA and singing certificate

Infos

- https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/[How to Create Your Own SSL Certificate Authority for Local HTTPS Development]
- https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs[OpenSSL Essentials: Working with SSL Certificates, Private Keys and CSRs]

Steps

. create CA

    openssl genrsa -des3 -out myCA.key 2048
    openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -out myCA.pem

. install myCA.pem into your browser ca settings
. generate server key

    openssl genrsa -out conf/server.key 2048

. generate CSR for the server key

    openssl req -new -key conf/server.key -out conf/server.csr

. generate a config file via copy the template example.ext to server.ext and adjust 
. signing the CSR with the CA

    openssl x509 -req -in conf/server.csr -CA ~/myCA/myCA.pem -CAkey ~/myCA/myCA.key -CAcreateserial -out conf/server.crt -days 365 -sha256 -extfile server.ext

