version: '3.4'

services:
  gitea:
    image: gitea/gitea:latest
    volumes: 
      - "gitea_data:/data"
    ports: 
      - "10022:22"
#      - "3000:3000"
    environment: 
      - ROOT_URL="https://localhost/gitea/"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.gitea.rule=PathPrefix(`/gitea`)"
      - "traefik.http.routers.gitea.middlewares=gitea@docker"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.gitea.stripprefix.prefixes=/gitea"

volumes: 
  gitea_data:
networks: 
  web: 
    external: 
      name: web